Repository ttbarnes/barnescode, pull requests merged in 2023-12, with the labels that each got.

#1 feat(home): V1 Home page
  .eslintrc.json
  .prettierrc.json
  components/Card.jsx
  components/Card.test.jsx
  components/Footer.jsx
  components/Footer.module.scss
  components/Footer.test.jsx
  components/Header.jsx
  components/Header.test.jsx
  components/Info.jsx
  components/Info.test.jsx
  components/Layout.jsx
  components/Layout.test.jsx
  components/Meta.js
  components/Meta.test.js
  constants/index.js
  jest.config.mjs
  next.config.js
  package-lock.json
  package.json
  pages/_app.js
  pages/index.js
  pages/index.test.js
  public/bg.jpg
  public/engineering.jpg
  public/engineering.svg
  public/logo-footer.svg
  public/logo.svg
  public/modernization.jpg
  public/mountain-4346633.jpg
  public/process-define.svg
  public/process-deliver.svg
  public/process-iterate.svg
  public/process-listen.svg
  public/products.svg
  public/rocket.svg
  public/scroll-arrow.svg
  public/services.svg
  public/software.svg
  public/user-research.jpg
  public/user-research.svg
  public/vercel.svg
  styles/Home.module.css
  styles/card.module.scss
  styles/globals.css
  styles/globals.scss
  styles/home.module.scss
  styles/info.module.scss
Labels: enhancement, feature

#3 feat(home): V1 Home page
  .eslintrc.json
  .prettierrc.json
  components/Card.jsx
  components/Card.test.jsx
  components/Footer.jsx
  components/Footer.module.scss
  components/Footer.test.jsx
  components/Header.jsx
  components/Header.test.jsx
  components/Info.jsx
  components/Info.test.jsx
  components/Layout.jsx
  components/Layout.test.jsx
  components/Meta.js
  components/Meta.test.js
  constants/index.js
  jest.config.mjs
  next.config.js
  package-lock.json
  package.json
  pages/_app.js
  pages/index.js
  public/bg.jpg
  public/engineering.jpg
  public/engineering.svg
  public/logo-footer.svg
  public/logo.svg
  public/modernization.jpg
  public/mountain-4346633.jpg
  public/process-define.svg
  public/process-deliver.svg
  public/process-iterate.svg
  public/process-listen.svg
  public/products.svg
  public/rocket.svg
  public/scroll-arrow.svg
  public/services.svg
  public/software.svg
  public/user-research.jpg
  public/user-research.svg
  public/vercel.svg
  styles/Home.module.css
  styles/card.module.scss
  styles/globals.css
  styles/globals.scss
  styles/home.module.scss
  styles/info.module.scss
Labels: enhancement, feature, dependencies, chore

#4 feat(contact): V1 contact page, various tech improvements
  .env.example
  .eslintrc.json
  .gitignore
  components/Button/Button.js
  components/Button/Button.module.scss
  components/Button/Button.test.js
  components/Button/index.js
  components/Card.jsx
  components/ContactForm/ContactForm-field-validation.test.js
  components/ContactForm/ContactForm.js
  components/ContactForm/ContactForm.test.js
  components/ContactForm/index.js
  components/ContactPanel/ContactPanel.js
  components/ContactPanel/ContactPanel.module.scss
  components/ContactPanel/ContactPanel.test.js
  components/ContactPanel/index.js
  components/Form/Form.js
  components/Form/Form.test.js
  components/Form/index.js
  components/FormField/FormField.js
  components/FormField/FormField.module.scss
  components/FormField/FormField.test.js
  components/FormField/index.js
  components/Info.jsx
  components/InlineErrorMessage/InlineErrorMessage.js
  components/InlineErrorMessage/InlineErrorMessage.module.scss
  components/InlineErrorMessage/InlineErrorMessage.test.js
  components/InlineErrorMessage/index.js
  components/Layout.jsx
  components/TextLink/TextLink.js
  components/TextLink/TextLink.module.scss
  components/TextLink/TextLink.test.js
  components/TextLink/index.js
  constants/field-ids.js
  constants/index.js
  constants/routes.js
  content-strings/index.js
  form-validation/contact/index.js
  form-validation/contact/index.test.js
  jest.config.mjs
  package-lock.json
  package.json
  pages/_app.js
  pages/api/contact.js
  pages/api/hello.js
  pages/contact/index.js
  pages/contact/thank-you/index.js
  pages/index.js
  public/bg-contact.jpg
  public/bg-home.jpg
  styles/contact.module.scss
  styles/form.module.scss
  styles/globals.scss
  styles/home.module.scss
  styles/info.module.scss
  test-helpers/index.js
Labels: enhancement, feature, technical improvement, dependencies, chore
